spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_popular
spring.datasource.username=postgres
spring.datasource.password=@ndrezA19
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=clinica-popular